version: '3.2'

services:
  db:
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    volumes:
      - ./docker/db/runit:/runit
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-9001}
      - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-f9001}

  backend:
    build:
      context: ./
      dockerfile: docker/backend/Dockerfile
    environment:
      - CY_ENV_OVERRIDE_FILE=/backend/.env.override
    volumes:
      - ./backend:/backend
      - ./.env:/backend/.env
      - ./.env.override:/backend/.env.override
    command: /runit

  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend/src:/frontend/src
      - ./.env:/.env
      - ./.env.override:/.env.override
    depends_on:
      - backend


  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    ports:
      - 1337:8000

  phabricator-db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '4444:3306'
    environment:
      MYSQL_USER: phabricator
      MYSQL_PASS: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phabricator:
    build:
      context: ./
      dockerfile: docker/phabricator/Dockerfile
    environment:
      PHABRICATOR_HOST: 127.0.0.1:1402
      PHABRICATOR_CDN: 127.0.0.1:1402
      MYSQL_HOST: phabricator-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      PHABRICATOR_REPOSITORY_PATH: /repos
    ports:
      - '1402:80'
    depends_on:
      - phabricator-db
    restart: on-failure:10
